---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: storage-apache
spec:
 accessModes:
  - ReadOnlyMany
 resources:
   requests:
        storage: 1Gi
storageClassName: glusterfs-storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: storage-nginx
spec:
 accessModes:
  - ReadOnlyMany
 resources:
   requests:
        storage: 1Gi
storageClassName: glusterfs-storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: storage-varnish
spec:
 accessModes:
  - ReadOnlyMany
 resources:
   requests:
        storage: 1Gi
storageClassName: glusterfs-storage

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: volume
  name: volume
spec:
  selector:
    app: volume
    deploymentconfig: volume
  template:
    metadata:
      labels:
        app: volume
        deploymentconfig: volume
    spec:
      containers:
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
      restartPolicy: Always
      volumes
        - name: volume-apache
          persistentVolumeClaim: 
            claimNam: storage-apache
        - name: volume-nginx
          persistentVolumeClaim:
            claimNam: storage-nginx
        - name: volume-varnish
          persistentVolumeClaim:
            claimNam: storage-varnish
---
