apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-apache
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-nginx
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-varnish
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs-storage

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      volumeMounts:
        - mountPath: /mnt/apache
          name: volume-apache
        - mountPath: /mnt/nginx
          name: volume-nginx
        - mountPath: /mnt/varnish
          name: volume-varnish
  restartPolicy: Always
  volumes:
    - name: volume-apache
      persistentVolumeClaim: 
        claimName: storage-apache
    - name: volume-nginx
      persistentVolumeClaim:
        claimName: storage-nginx
    - name: volume-varnish
      persistentVolumeClaim:
        claimName: storage-varnish
