---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: storage-apache
spec:
 accessModes:
  - ReadOnlyMany
 resources:
   requests:
        storage: 1Gi
storageClassName: glusterfs-storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: storage-nginx
spec:
 accessModes:
  - ReadOnlyMany
 resources:
   requests:
        storage: 1Gi
storageClassName: glusterfs-storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: storage-varnish
spec:
 accessModes:
  - ReadOnlyMany
 resources:
   requests:
        storage: 1Gi
storageClassName: glusterfs-storage

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: volumes
  name: volumes
spec:
  replicas: 1
  selector:
    app: volumes
    deploymentconfig: volumes
  template:
    metadata:
      labels:
        app: volumes
        deploymentconfig: volumes
    spec:
      containers:
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
      restartPolicy: Always
      volumes:
        - name: volume-apache
          persistentVolumeClaim: 
            claimNam: storage-apache
        - name: volume-nginx
          persistentVolumeClaim:
            claimNam: storage-nginx
        - name: volume-varnish
          persistentVolumeClaim:
            claimNam: storage-varnish
---
